### ISSUE TITLE
Cannot plan a route over un-mapped tracks

### ISSUE THREAD

**Issue by lefou** [cxberlin/brouter#2]
I'm currently not able to plan a route along knows tracks, if they are not properly mapped. I guess, we need some "off-road" planning feature here.

I my screenshot, you can see the track as way-points, but cxb-routenplanner insists to route another way.

![grafik](https://user-images.githubusercontent.com/1321393/111343868-203f0600-867c-11eb-953e-889270f2685e.png)

Here you see the same map without the route (`m` key pressed).

![grafik](https://user-images.githubusercontent.com/1321393/111344561-c428b180-867c-11eb-8f94-cbf633b48d12.png)

**Comment by stefankeidel** [comment]
Hey, thanks for the report! Do you have an example link so we can reproduce this? [brouter-web is basically state-less, all state is kept in the URL so it's easily shared]

my guess is there's some attribute on that path/way that prevents the gravel profile from routing there.

**Comment by lefou** [comment]
Sorry, but the URL in the address bar is still the entry URL. How can I reveal the full URL?

**Comment by lefou** [comment]
But here is the same map: https://cycling.waymarkedtrails.org/#?map=15!51.5065!14.1385

**Comment by stefankeidel** [comment]
Ah, I was able to make out where this is -- "Lausitzer Seeland"

So the road you're trying to route on is this one: https://www.openstreetmap.org/way/445076587

It has the attribute `access=private`, which, [according to OpenStreetMap](https://wiki.openstreetmap.org/wiki/Tag:access%3Dprivate) means 

> The access=private tag is generally used in combination with the road network tags to indicate that the road is not to be used by the general public, and on other facilities. Access is only with permission on an individual basis. 

If you wanted to change how this is handled, you could edit that part of the profile. There's a cost calculation around this at and above [Line 117](https://github.com/cxberlin/brouter-profiles/blob/main/gravel.brf#L117). 

I haven't been there, if the road is actually not private and signs allow access, then you could change that attribute in OSM. Our route planner would pick that up soon™

**Comment by stefankeidel** [comment]
Oh I should note, we will definitely not change this in the routing profile we provide, as we don't want to route people on private roads. This is rarely a problem in Germany, but elsewhere you can get into trouble really fast. 

That said, the web brouter lets you edit the profile on the fly in the right hand menu. So if you want to go that way, you're free to do so :)

<img width="643" alt="image" src="https://user-images.githubusercontent.com/1188614/111347241-4a45f780-867f-11eb-96b3-aeb9d4f066ef.png">

Closing this for now. Thanks for using and testing the tool so thoroughly!

**Comment by lefou** [comment]
Thanks for the fast feedback. Beside changing the overall routing algorithm (via config), is there some other tool to force some specific (non-)paths, e.g. hike-a-bike sections?

**Comment by stefankeidel** [comment]
Uhm, no I don't think that's possible at the moment. There has to be what OpenStreetMap calls a `way`. Though you'd be surprised what tiny footpaths are actually in that database. As long as access is not completely illegal (like in your case), you should be able to force the route on those paths but putting a few points there. Routing only takes place between pairs of points.

That includes steep hiking paths and such ... I've certainly found myself pushing my loaded bike up questionable sections in the mountains when planning with this profile ;-). 



There are tools (other than brouter-web) that use the Brouter routing engine (meaning you can plug in our routing profile) as backend that let you pick different routing profiles between points or draw tracks without any routing. You could try that, for example qmapshack. It's not a simple tool to use as I understand though ;-)

**Comment by lefou** [comment]
@stefankeidel Very useful information. Thank you!
